import tkinter as tk
from tkinter import ttk


class AbaGatinho:

    def __init__(self, app):
        self.frame = tk.Frame(app.window, background="#68BCED")

        self.secondFrame = tk.Frame(self.frame)
        self.secondFrame.place(x=140, y=20, height=325, width=335)
        self.secondFrame.configure(relief='flat')
        self.secondFrame.configure(borderwidth="2")
        self.secondFrame.configure(background="#60F7DD")

        self.NameLabel = tk.Label(self.secondFrame)
        self.NameLabel.place(x=20, y=10, height=22, width=64)
        self.NameLabel.configure(activebackground="#f9f9f9")
        self.NameLabel.configure(activeforeground="black")
        self.NameLabel.configure(anchor='w')
        self.NameLabel.configure(background="#60F7DD")
        self.NameLabel.configure(disabledforeground="#a3a3a3")
        self.NameLabel.configure(font="-family {Small Fonts} -size 14")
        self.NameLabel.configure(foreground="#5484d6")
        self.NameLabel.configure(highlightbackground="#d9d9d9")
        self.NameLabel.configure(highlightcolor="black")
        self.NameLabel.configure(text='''Nome:''')

        self.NameInput = tk.Entry(self.secondFrame)
        self.NameInput.place(x=90, y=10, height=20, width=224)
        self.NameInput.configure(background="white")
        self.NameInput.configure(disabledforeground="#a3a3a3")
        self.NameInput.configure(font="-family {Small Fonts} -size 8")
        self.NameInput.configure(foreground="#000000")
        self.NameInput.configure(highlightbackground="#d9d9d9")
        self.NameInput.configure(highlightcolor="black")
        self.NameInput.configure(insertbackground="black")
        self.NameInput.configure(readonlybackground="#f0f0f0f0f0f0")
        self.NameInput.configure(relief="flat")
        self.NameInput.configure(selectbackground="blue")
        self.NameInput.configure(selectforeground="white")

        self.Vac = tk.IntVar()

        self.VacCheck = tk.Checkbutton(self.secondFrame, onvalue=1, offvalue=0)
        self.VacCheck.place(x=10, y=289, height=26, width=111)
        self.VacCheck.configure(activebackground="#60F7DD")
        self.VacCheck.configure(activeforeground="#5484d6")
        self.VacCheck.configure(anchor='w')
        self.VacCheck.configure(background="#60F7DD")
        self.VacCheck.configure(borderwidth="0")
        self.VacCheck.configure(disabledforeground="#a3a3a3")
        self.VacCheck.configure(font="-family {Small Fonts} -size 14")
        self.VacCheck.configure(foreground="#5484d6")
        self.VacCheck.configure(highlightbackground="#d9d9d9")
        self.VacCheck.configure(highlightcolor="black")
        self.VacCheck.configure(justify='left')
        self.VacCheck.configure(offrelief="flat")
        self.VacCheck.configure(overrelief="flat")
        self.VacCheck.configure(text='''Vacinado''')
        self.VacCheck.configure(variable=self.Vac)

        self.Sono = tk.IntVar()

        self.SonoCheck = tk.Checkbutton(self.secondFrame)
        self.SonoCheck.place(x=210, y=289, height=26, width=111)
        self.SonoCheck.configure(activebackground="#60F7DD")
        self.SonoCheck.configure(activeforeground="#5484d6")
        self.SonoCheck.configure(anchor='w')
        self.SonoCheck.configure(background="#60F7DD")
        self.SonoCheck.configure(borderwidth="0")
        self.SonoCheck.configure(disabledforeground="#a3a3a3")
        self.SonoCheck.configure(font="-family {Small Fonts} -size 14")
        self.SonoCheck.configure(foreground="#5484d6")
        self.SonoCheck.configure(highlightbackground="#d9d9d9")
        self.SonoCheck.configure(highlightcolor="black")
        self.SonoCheck.configure(justify='left')
        self.SonoCheck.configure(offrelief="flat")
        self.SonoCheck.configure(overrelief="flat")
        self.SonoCheck.configure(text='''Dormindo''')
        self.SonoCheck.configure(variable=self.Sono)

        self.IdadeLabel = tk.Label(self.secondFrame)
        self.IdadeLabel.place(x=20, y=41, height=22, width=64)
        self.IdadeLabel.configure(activebackground="#f9f9f9")
        self.IdadeLabel.configure(activeforeground="black")
        self.IdadeLabel.configure(anchor='w')
        self.IdadeLabel.configure(background="#60F7DD")
        self.IdadeLabel.configure(disabledforeground="#a3a3a3")
        self.IdadeLabel.configure(font="-family {Small Fonts} -size 14")
        self.IdadeLabel.configure(foreground="#5484d6")
        self.IdadeLabel.configure(highlightbackground="#d9d9d9")
        self.IdadeLabel.configure(highlightcolor="black")
        self.IdadeLabel.configure(text='''Idade:''')

        self.IdadeInput = tk.Entry(self.secondFrame)
        self.IdadeInput.place(x=90, y=41, height=20, width=74)
        self.IdadeInput.configure(background="white")
        self.IdadeInput.configure(disabledforeground="#a3a3a3")
        self.IdadeInput.configure(font="-family {Small Fonts} -size 8")
        self.IdadeInput.configure(foreground="#000000")
        self.IdadeInput.configure(highlightbackground="#d9d9d9")
        self.IdadeInput.configure(highlightcolor="black")
        self.IdadeInput.configure(insertbackground="black")
        self.IdadeInput.configure(readonlybackground="#f0f0f0f0f0f0")
        self.IdadeInput.configure(relief="flat")
        self.IdadeInput.configure(selectbackground="blue")
        self.IdadeInput.configure(selectforeground="white")

        self.FomeScale = tk.Scale(self.secondFrame, from_=0.0, to=100.0)
        self.FomeScale.place(x=100, y=72, height=43, width=216)
        self.FomeScale.configure(activebackground="#60F7DD")
        self.FomeScale.configure(background="#60F7DD")
        self.FomeScale.configure(borderwidth="0")
        self.FomeScale.configure(font="-family {Small Fonts} -size 8 -weight bold")
        self.FomeScale.configure(foreground="#5484d6")
        self.FomeScale.configure(highlightbackground="#60F7DD")
        self.FomeScale.configure(highlightcolor="black")
        self.FomeScale.configure(orient="horizontal")
        self.FomeScale.configure(troughcolor="#5484d6")

        self.FomeLabel = tk.Label(self.secondFrame)
        self.FomeLabel.place(x=20, y=83, height=21, width=64)
        self.FomeLabel.configure(activebackground="#f9f9f9")
        self.FomeLabel.configure(activeforeground="black")
        self.FomeLabel.configure(anchor='w')
        self.FomeLabel.configure(background="#60F7DD")
        self.FomeLabel.configure(disabledforeground="#a3a3a3")
        self.FomeLabel.configure(font="-family {Small Fonts} -size 14")
        self.FomeLabel.configure(foreground="#5484d6")
        self.FomeLabel.configure(highlightbackground="#d9d9d9")
        self.FomeLabel.configure(highlightcolor="black")
        self.FomeLabel.configure(text='''Fome:''')

        self.EnergiaLabel = tk.Label(self.secondFrame)
        self.EnergiaLabel.place(x=20, y=134, height=32, width=74)
        self.EnergiaLabel.configure(activebackground="#f9f9f9")
        self.EnergiaLabel.configure(activeforeground="black")
        self.EnergiaLabel.configure(anchor='w')
        self.EnergiaLabel.configure(background="#60F7DD")
        self.EnergiaLabel.configure(disabledforeground="#a3a3a3")
        self.EnergiaLabel.configure(font="-family {Small Fonts} -size 14")
        self.EnergiaLabel.configure(foreground="#5484d6")
        self.EnergiaLabel.configure(highlightbackground="#d9d9d9")
        self.EnergiaLabel.configure(highlightcolor="black")
        self.EnergiaLabel.configure(text='''Energia:''')

        self.EnergiaScale = tk.Scale(self.secondFrame, from_=0.0, to=100.0)
        self.EnergiaScale.place(x=100, y=124, height=43, width=216)
        self.EnergiaScale.configure(activebackground="#60F7DD")
        self.EnergiaScale.configure(background="#60F7DD")
        self.EnergiaScale.configure(borderwidth="0")
        self.EnergiaScale.configure(font="-family {Small Fonts} -size 8 -weight bold")
        self.EnergiaScale.configure(foreground="#5484d6")
        self.EnergiaScale.configure(highlightbackground="#60F7DD")
        self.EnergiaScale.configure(highlightcolor="black")
        self.EnergiaScale.configure(orient="horizontal")
        self.EnergiaScale.configure(troughcolor="#5484d6")

        self.SaudeLabel = tk.Label(self.secondFrame)
        self.SaudeLabel.place(x=20, y=186, height=21, width=64)
        self.SaudeLabel.configure(activebackground="#f9f9f9")
        self.SaudeLabel.configure(activeforeground="black")
        self.SaudeLabel.configure(anchor='w')
        self.SaudeLabel.configure(background="#60F7DD")
        self.SaudeLabel.configure(cursor="fleur")
        self.SaudeLabel.configure(disabledforeground="#a3a3a3")
        self.SaudeLabel.configure(font="-family {Small Fonts} -size 14")
        self.SaudeLabel.configure(foreground="#5484d6")
        self.SaudeLabel.configure(highlightbackground="#d9d9d9")
        self.SaudeLabel.configure(highlightcolor="black")
        self.SaudeLabel.configure(text='''Saúde:''')

        self.SaudeScale = tk.Scale(self.secondFrame, from_=0.0, to=100.0)
        self.SaudeScale.place(x=100, y=176, height=43, width=216)
        self.SaudeScale.configure(activebackground="#60F7DD")
        self.SaudeScale.configure(background="#60F7DD")
        self.SaudeScale.configure(borderwidth="0")
        self.SaudeScale.configure(font="-family {Small Fonts} -size 8 -weight bold")
        self.SaudeScale.configure(foreground="#5484d6")
        self.SaudeScale.configure(highlightbackground="#60F7DD")
        self.SaudeScale.configure(highlightcolor="black")
        self.SaudeScale.configure(orient="horizontal")
        self.SaudeScale.configure(troughcolor="#5484d6")

        self.FelizLabel = tk.Label(self.secondFrame)
        self.FelizLabel.place(x=20, y=237, height=22, width=44)
        self.FelizLabel.configure(activebackground="#f9f9f9")
        self.FelizLabel.configure(activeforeground="black")
        self.FelizLabel.configure(anchor='w')
        self.FelizLabel.configure(background="#60F7DD")
        self.FelizLabel.configure(cursor="fleur")
        self.FelizLabel.configure(disabledforeground="#a3a3a3")
        self.FelizLabel.configure(font="-family {Small Fonts} -size 14")
        self.FelizLabel.configure(foreground="#5484d6")
        self.FelizLabel.configure(highlightbackground="#d9d9d9")
        self.FelizLabel.configure(highlightcolor="black")
        self.FelizLabel.configure(text='''Feliz:''')

        self.FelizScale = tk.Scale(self.secondFrame, from_=0.0, to=100.0)
        self.FelizScale.place(x=100, y=227, height=43, width=216)
        self.FelizScale.configure(activebackground="#60F7DD")
        self.FelizScale.configure(background="#60F7DD")
        self.FelizScale.configure(borderwidth="0")
        self.FelizScale.configure(font="-family {Small Fonts} -size 8 -weight bold")
        self.FelizScale.configure(foreground="#5484d6")
        self.FelizScale.configure(highlightbackground="#60F7DD")
        self.FelizScale.configure(highlightcolor="black")
        self.FelizScale.configure(orient="horizontal")
        self.FelizScale.configure(troughcolor="#5484d6")

        self.Tipo = ttk.Combobox(self.secondFrame)
        self.Tipo.place(x=170, y=40, height=21, width=143)
        self.Tipo.configure(font="-family {Small Fonts} -size 10")
        self.Tipo.configure(takefocus="")
        self.Tipo.configure(values=['Adotado', 'Comprado', 'Resgatado'])
        self.Tipo.configure(state='readonly')

    def del_inputs(self):
        self.NameInput.delete(0, tk.END)
        self.IdadeInput.delete(0, tk.END)
        self.FomeScale.set(0)
        self.EnergiaScale.set(0)
        self.SaudeScale.set(0)
        self.FelizScale.set(0)
        self.VacCheck.deselect()
        self.SonoCheck.deselect()
